version: '3.4'

services:
  api.scrapping:
    image: ${DOCKER_REGISTRY-}apiscrapping
    build:
      context: .
      dockerfile: API.Scrapping/Dockerfile
  scrappingdb:
    image: mongo
  mgclient:
    image: mongoclient/mongoclient

volumes:
    mongodata:
